// See: https://book.mql4.com/appendix/errors
export const ERROR_CODES: any = {
	// Error codes returned from a trade server or client terminal:
	0: [ "No error returned.", "ERR_NO_ERROR" ],
	1: [ "No error returned", "ERR_NO_RESULT" ],
	2: [ "Common error.", "ERR_COMMON_ERROR" ],
	3: [ "Invalid trade parameters.", "ERR_INVALID_TRADE_PARAMETERS" ],
	4: [ "Trade server is busy.", "ERR_SERVER_BUSY" ],
	5: [ "Old version of the client terminal.", "ERR_OLD_VERSION" ],
	6: [ "No connection with trade server.", "ERR_NO_CONNECTION" ],
	7: [ "Not enough rights.", "ERR_NOT_ENOUGH_RIGHTS" ],
	8: [ "Too frequent requests.", "ERR_TOO_FREQUENT_REQUESTS" ],
	9: [ "Malfunctional trade operation.", "ERR_MALFUNCTIONAL_TRADE" ],
	64: [ "Account disabled.", "ERR_ACCOUNT_DISABLED" ],
	65: [ "Invalid account.", "ERR_INVALID_ACCOUNT" ],
	128: [ "Trade timeout.", "ERR_TRADE_TIMEOUT" ],
	129: [ "Invalid price.", "ERR_INVALID_PRICE" ],
	130: [ "Invalid stops.", "ERR_INVALID_STOPS" ],
	131: [ "Invalid trade volume.", "ERR_INVALID_TRADE_VOLUME" ],
	132: [ "Market is closed.", "ERR_MARKET_CLOSED" ],
	133: [ "Trade is disabled.", "ERR_TRADE_DISABLED" ],
	134: [ "Not enough money.", "ERR_NOT_ENOUGH_MONEY" ],
	135: [ "Price changed.", "ERR_PRICE_CHANGED" ],
	136: [ "Off quotes.", "ERR_OFF_QUOTES" ],
	137: [ "Broker is busy.", "ERR_BROKER_BUSY" ],
	138: [ "Requote.", "ERR_REQUOTE" ],
	139: [ "Order is locked.", "ERR_ORDER_LOCKED" ],
	140: [ "Long positions only allowed.", "ERR_LONG_POSITIONS_ONLY_ALLOWED" ],
	141: [ "Too many requests.", "ERR_TOO_MANY_REQUESTS" ],
	145: [ "Modification denied because an order is too close to market.", "ERR_TRADE_MODIFY_DENIED" ],
	146: [ "Trade context is busy.", "ERR_TRADE_CONTEXT_BUSY" ],
	147: [ "Expirations are denied by broker.", "ERR_TRADE_EXPIRATION_DENIED" ],
	148: [ "The amount of opened and pending orders has reached the limit set by a broker.", "ERR_TRADE_TOO_MANY_ORDERS" ],
	// MQL4 run time error codes:
	4000: [ "No error.", "ERR_NO_MQLERROR" ],
	4001: [ "Wrong function pointer.", "ERR_WRONG_FUNCTION_POINTER" ],
	4002: [ "Array index is out of range.", "ERR_ARRAY_INDEX_OUT_OF_RANGE" ],
	4003: [ "No memory for function call stack.", "ERR_NO_MEMORY_FOR_FUNCTION_CALL_STACK" ],
	4004: [ "Recursive stack overflow.", "ERR_RECURSIVE_STACK_OVERFLOW" ],
	4005: [ "Not enough stack for parameter.", "ERR_NOT_ENOUGH_STACK_FOR_PARAMETER" ],
	4006: [ "No memory for parameter string.", "ERR_NO_MEMORY_FOR_PARAMETER_STRING" ],
	4007: [ "No memory for temp string.", "ERR_NO_MEMORY_FOR_TEMP_STRING" ],
	4008: [ "Not initialized string.", "ERR_NOT_INITIALIZED_STRING" ],
	4009: [ "Not initialized string in an array.", "ERR_NOT_INITIALIZED_ARRAYSTRING" ],
	4010: [ "No memory for an array string.", "ERR_NO_MEMORY_FOR_ARRAYSTRING" ],
	4011: [ "Too long string.", "ERR_TOO_LONG_STRING" ],
	4012: [ "Remainder from zero divide.", "ERR_REMAINDER_FROM_ZERO_DIVIDE" ],
	4013: [ "Zero divide.", "ERR_ZERO_DIVIDE" ],
	4014: [ "Unknown command.", "ERR_UNKNOWN_COMMAND" ],
	4015: [ "Wrong jump.", "ERR_WRONG_JUMP" ],
	4016: [ "Not initialized array.", "ERR_NOT_INITIALIZED_ARRAY" ],
	4017: [ "DLL calls are not allowed.", "ERR_DLL_CALLS_NOT_ALLOWED" ],
	4018: [ "Cannot load library.", "ERR_CANNOT_LOAD_LIBRARY" ],
	4019: [ "Cannot call function.", "ERR_CANNOT_CALL_FUNCTION" ],
	4020: [ "EA function calls are not allowed.", "ERR_EXTERNAL_EXPERT_CALLS_NOT_ALLOWED" ],
	4021: [ "Not enough memory for a string returned from a function.", "ERR_NOT_ENOUGH_MEMORY_FOR_RETURNED_STRING" ],
	4022: [ "System is busy.", "ERR_SYSTEM_BUSY" ],
	4050: [ "Invalid function parameters count.", "ERR_INVALID_FUNCTION_PARAMETERS_COUNT" ],
	4051: [ "Invalid function parameter value.", "ERR_INVALID_FUNCTION_PARAMETER_VALUE" ],
	4052: [ "String function internal error.", "ERR_STRING_FUNCTION_INTERNAL_ERROR" ],
	4053: [ "Some array error.", "ERR_SOME_ARRAY_ERROR" ],
	4054: [ "Incorrect series array using.", "ERR_INCORRECT_SERIES_ARRAY_USING" ],
	4055: [ "Custom indicator error.", "ERR_CUSTOM_INDICATOR_ERROR" ],
	4056: [ "Arrays are incompatible.", "ERR_INCOMPATIBLE_ARRAYS" ],
	4057: [ "Global variables processing error.", "ERR_GLOBAL_VARIABLES_PROCESSING_ERROR" ],
	4058: [ "Global variable not found.", "ERR_GLOBAL_VARIABLE_NOT_FOUND" ],
	4059: [ "Function is not allowed in testing mode.", "ERR_FUNCTION_NOT_ALLOWED_IN_TESTING_MODE" ],
	4060: [ "Function is not confirmed.", "ERR_FUNCTION_NOT_CONFIRMED" ],
	4061: [ "Mail sending error.", "ERR_SEND_MAIL_ERROR" ],
	4062: [ "String parameter expected.", "ERR_STRING_PARAMETER_EXPECTED" ],
	4063: [ "Integer parameter expected.", "ERR_INTEGER_PARAMETER_EXPECTED" ],
	4064: [ "Double parameter expected.", "ERR_DOUBLE_PARAMETER_EXPECTED" ],
	4065: [ "Array as parameter expected.", "ERR_ARRAY_AS_PARAMETER_EXPECTED" ],
	4066: [ "Requested history data in updating state.", "ERR_HISTORY_WILL_UPDATED" ],
	4067: [ "Some error in trade operation execution.", "ERR_TRADE_ERROR" ],
	4099: [ "End of a file.", "ERR_END_OF_FILE" ],
	4100: [ "Some file error.", "ERR_SOME_FILE_ERROR" ],
	4101: [ "Wrong file name.", "ERR_WRONG_FILE_NAME" ],
	4102: [ "Too many opened files.", "ERR_TOO_MANY_OPENED_FILES" ],
	4103: [ "Cannot open file.", "ERR_CANNOT_OPEN_FILE" ],
	4104: [ "Incompatible access to a file.", "ERR_INCOMPATIBLE_ACCESS_TO_FILE" ],
	4105: [ "No order selected.", "ERR_NO_ORDER_SELECTED" ],
	4106: [ "Unknown symbol.", "ERR_UNKNOWN_SYMBOL" ],
	4107: [ "Invalid price.", "ERR_INVALID_PRICE_PARAM" ],
	4108: [ "Invalid ticket.", "ERR_INVALID_TICKET" ],
	4109: [ "Trade is not allowed.", "ERR_TRADE_NOT_ALLOWED" ],
	4110: [ "Longs are not allowed.", "ERR_LONGS_NOT_ALLOWED" ],
	4111: [ "Shorts are not allowed.", "ERR_SHORTS_NOT_ALLOWED" ],
	4200: [ "Object already exists.", "ERR_OBJECT_ALREADY_EXISTS" ],
	4201: [ "Unknown object property.", "ERR_UNKNOWN_OBJECT_PROPERTY" ],
	4202: [ "Object does not exist.", "ERR_OBJECT_DOES_NOT_EXIST" ],
	4203: [ "Unknown object type.", "ERR_UNKNOWN_OBJECT_TYPE" ],
	4204: [ "No object name.", "ERR_NO_OBJECT_NAME" ],
	4205: [ "Object coordinates error.", "ERR_OBJECT_COORDINATES_ERROR" ],
	4206: [ "No specified subwindow.", "ERR_NO_SPECIFIED_SUBWINDOW" ],
	4207: [ "Some error in object operation.", "ERR_SOME_OBJECT_ERROR" ]
};
